### ISSUE TITLE
Deploy to Vercel shows blank page.

### ISSUE THREAD

**Issue by marke-dev** [LiveDuo/destack-starter-beta#2]
https://destack-starter-beta-inky.vercel.app/

Just shows blank page.  No visible errors

**Comment by LiveDuo** [comment]
Hey @marke-dev,

That shouldn't be the case.

There was a bug a few days ago with the beta. 

I fixed it and updated the template so if you clone used the repo before 3-4 days you might want to update Destack's beta version.

**Comment by marke-dev** [comment]
I think it is just the vercel deploy button itself in the README.  I ran this locally and it works fine

**Comment by LiveDuo** [comment]
Should be because the default page is blank. When you make changes and redeploy it should show them in Vercel too.
